# Generated by Django 4.2.3 on 2023-07-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='choices',
            field=models.CharField(choices=[('started', 'Started'), ('finished', 'Finished')], default='started', max_length=20),
        ),
    ]
