# Generated by Django 4.2.3 on 2023-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='choices',
            field=models.CharField(choices=[('started', 'Start'), ('finished', 'Finished')], default='started', max_length=20),
        ),
    ]
